import type { TableDataType } from "../types/TableDataType";
import profile_image from "../assets/images/profile.png";

export const tableData: TableDataType[] = [
  {
    name: "John Doe",
    username: "@John",
    selected: false,
    status: "Active",
    subStatus: "Busy",
    role: "Product Designer",
    email: "john@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Jane Smith",
    username: "@Jane",
    selected: false,
    status: "Inactive",
    subStatus: "On Leave",
    role: "Frontend Developer",
    email: "jane.smith@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Mike Brown",
    username: "@Mike",
    selected: false,
    status: "Active",
    subStatus: "Busy",
    role: "Backend Engineer",
    email: "mike.brown@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Emily Clark",
    username: "@Emily",
    selected: false,
    status: "Inactive",
    subStatus: "Terminated",
    role: "Project Manager",
    email: "emily.clark@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "David Lee",
    username: "@David",
    selected: false,
    status: "Inactive",
    subStatus: "Terminated",
    role: "QA Analyst",
    email: "david.lee@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Sophia White",
    username: "@Sophia",
    selected: false,
    status: "Active",
    subStatus: "Away",
    role: "Content Strategist",
    email: "sophia.white@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "David Lee",
    username: "@David",
    selected: false,
    status: "Inactive",
    subStatus: "Terminated",
    role: "QA Analyst",
    email: "david.lee@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Sophia White",
    username: "@Sophia",
    selected: false,
    status: "Active",
    subStatus: "Away",
    role: "Content Strategist",
    email: "sophia.white@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Jane Smith",
    username: "@Jane",
    selected: false,
    status: "Inactive",
    subStatus: "On Leave",
    role: "Frontend Developer",
    email: "jane.smith@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Mike Brown",
    username: "@Mike",
    selected: false,
    status: "Active",
    subStatus: "Busy",
    role: "Backend Engineer",
    email: "mike.brown@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Emily Clark",
    username: "@Emily",
    selected: false,
    status: "Inactive",
    subStatus: "Terminated",
    role: "Project Manager",
    email: "emily.clark@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Jane Smith",
    username: "@Jane",
    selected: false,
    status: "Inactive",
    subStatus: "On Leave",
    role: "Frontend Developer",
    email: "jane.smith@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Mike Brown",
    username: "@Mike",
    selected: false,
    status: "Active",
    subStatus: "Busy",
    role: "Backend Engineer",
    email: "mike.brown@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
  {
    name: "Emily Clark",
    username: "@Emily",
    selected: false,
    status: "Inactive",
    subStatus: "Terminated",
    role: "Project Manager",
    email: "emily.clark@email.com",
    teams: ["Design", "Product", "Marketing"],
    image: profile_image,
  },
];
